updated autosaver script from main repo

diff --git a/autosaver b/autosaver
--- a/autosaver
+++ b/autosaver
@@ -15,26 +15,12 @@ LOCAL_BIN_PATH="$LOCAL_BIN_PATH_DIR/autosaver"
 REMOTE_RELEASE_URL="https://github.com/daniele47/autosaver/releases/latest/download"
 REMOTE_BIN_NAME=""
 REMOTE_RELEASE_URL_BIN=""
-# platform
-PLATFORM="$(uname -s)"
-ARCHITECTURE="$(uname -m)"
-
-function download_url() {
-    local url="$1"
-    local output="$2"
-    if command -v curl &>/dev/null; then
-        curl -L --fail --show-error --progress-bar --output "$output" "$url"
-    elif command -v wget &>/dev/null; then
-        wget --no-verbose --show-progress --output-document="$output" "$url"
-    else
-        echo "ERROR: Neither curl nor wget found. Please install one." >&2
-        return 1
-    fi
-}
 
 # update/uninstall
 if [[ ! -f "$LOCAL_BIN_PATH" && ! -v UNINSTALL || -v INSTALL ]]; then
     # get platform / os dependent variables populated
+    PLATFORM="$(uname -s)"
+    ARCHITECTURE="$(uname -m)"
     case "$PLATFORM" in
     Linux)
         case "$ARCHITECTURE" in
@@ -51,15 +37,25 @@ if [[ ! -f "$LOCAL_BIN_PATH" && ! -v UNINSTALL || -v INSTALL ]]; then
     rm -rf "$LOCAL_BIN_PATH_DIR"
     mkdir -p "$LOCAL_BIN_PATH_DIR"
 
+    # download and install operations
     echo "(1/3) Downloading latest archive release..."
     REMOTE_RELEASE_URL_BIN="$REMOTE_RELEASE_URL/$REMOTE_BIN_NAME"
-    download_url "$REMOTE_RELEASE_URL_BIN" "$LOCAL_BIN_PATH_DIR/archive.tar.gz"
+    url="$REMOTE_RELEASE_URL_BIN"
+    output=$LOCAL_BIN_PATH_DIR/archive.tar.gz""
+    if command -v curl &>/dev/null; then
+        curl -L --fail --show-error --progress-bar --output "$output" "$url"
+    elif command -v wget &>/dev/null; then
+        wget --no-verbose --show-progress --output-document="$output" "$url"
+    else
+        echo "ERROR: Neither curl nor wget found. Please install one." >&2
+        return 1
+    fi
 
     echo "(2/3) Decompossing downloaded archive..."
-    tar -xzf "$LOCAL_BIN_PATH_DIR/archive.tar.gz" -C "$LOCAL_BIN_PATH_DIR"
+    tar -xzf "$output" -C "$LOCAL_BIN_PATH_DIR"
 
     echo "(3/3) Cleanup temporary files..."
-    rm "$LOCAL_BIN_PATH_DIR/archive.tar.gz"
+    rm "$output"
 
     echo -n "Autosaver installed/updated: "
     "$LOCAL_BIN_PATH" --version
